image: tmaier/docker-compose:latest

variables:
  DOCKER_DRIVER: overlay2

stages:
    - build
    - deploy

build:
  stage: build
  script:
    - "docker build -t $CI_PROJECT_NAME/$CI_COMMIT_REF_NAME:latest ."

deploy_production:
  stage: deploy
  script:
    - "docker-compose down && docker-compose up -d"
  environment:
    name: production
  only:
  - master
